COMMON: &common
  SECRET_KEY: insecure
  SECURITY_POST_LOGIN_VIEW: '/profile'
  SQLALCHEMY_DATABASE_URI: sqlite:////tmp/test.db
  ADMIN_CREDENTIALS: 'admin,password'

  SECURITY_TRACKABLE: True
  SOCIAL_CONNECT_ALLOW_VIEW: '/profile'

  SOCIAL_FACEBOOK:
    consumer_key: 'key'
    consumer_secret: 'secret'
    request_token_params:
      scope: 'email,publish_stream'

DEVELOPMENT: &development
  <<: *common
  DEBUG: True

PRODUCTION: &production
  <<: *common
  DEBUG: True
  SECURITY_PASSWORD_HASH: bcrypt
  SOCIAL_APP_URL: http://flask-social-example.herokuapp.com/
